version: "2"
run:
  go: "1.22"
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - noctx
    - revive
  settings:
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - commentedOutCode
        - dupImport
        - emptyStringTest
        - equalFold
        - hexLiteral
        - indexAlloc
        - initClause
        - methodExprCall
        - nilValReturn
        - rangeValCopy
        - stringXbytes
        - typeUnparen
        - unnamedResult
        - unnecessaryBlock
        - weakCond
        - yodaStyleExpr
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - gosec
        text: 'G404:'
      - linters:
          - staticcheck
        text: 'SA1019:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
