version: 2

project_name: talon

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: talon
    main: ./cmd/talon/
    binary: talon
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # goreleaser-cross v1.25.7: darwin and windows cross-compilation from Linux is
    # broken (osxcross passes -arch to host gcc). Ship linux/amd64 via CI; macOS
    # users build natively with `go install` or `make build`.
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: amd64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/dativo-io/talon/internal/cmd.Version={{.Version}}
      - -X github.com/dativo-io/talon/internal/cmd.Commit={{.ShortCommit}}
      - -X github.com/dativo-io/talon/internal/cmd.BuildDate={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: 'New Features'
      regexp: '^feat:'
    - title: 'Bug Fixes'
      regexp: '^fix:'
    - title: 'Security'
      regexp: '^sec:'

sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.spdx.json"

dockers:
  - image_templates:
      - "ghcr.io/dativo-io/talon:{{ .Version }}"
      - "ghcr.io/dativo-io/talon:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/dativo-io/talon:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--build-arg VERSION={{.Version}}"
      - "--build-arg COMMIT={{.Commit}}"
      - "--build-arg BUILD_DATE={{.Date}}"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=talon"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dativo-io/talon"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

release:
  github:
    owner: dativo-io
    name: talon
  draft: false
  prerelease: auto
