package tests

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestNoLivePostureVocabulary is the #442 grep guard: the live non-enforcing
// postures (gateway shadow/log_only, MCP passthrough/shadow, native
// audit.observation_only, tool schema_validation shadow/disabled) and their
// operator surfaces (`talon enforce`, `--gateway-mode`, TALON_QUICKSTART_MODE,
// enforcement_mode/shadow_summary JSON) were removed. Their vocabulary must
// not describe the current product in user-facing surfaces.
//
// A line is permitted only when it carries an explicit "#442" note (a
// migration diagnostic, a "removed in #442" doc note, or a LEGACY evidence
// field row), or when it belongs to an allowlisted historical file or to a
// feature-local vocabulary that #442 deliberately left alone (memory and
// enrichment "shadow" evaluation, attachment action_on_detection).
func TestNoLivePostureVocabulary(t *testing.T) {
	repoRoot := filepath.Clean(filepath.Join("..", "."))

	scanRoots := []string{
		"README.md",
		"ROADMAP.md",
		"LIMITATIONS.md",
		"docs",
		"examples",
		"schemas",
		"web",
		filepath.Join("internal", "cmd", "templates"),
		filepath.Join("internal", "pack", "templates"),
		filepath.Join("tests", "smoke_lib.sh"),
		filepath.Join("tests", "smoke_test.sh"),
		filepath.Join("tests", "smoke_sections"),
	}

	patterns := []string{
		"gateway.mode",
		"proxy.mode",
		"observation_only",
		"schema_validation",
		"talon enforce status",
		"talon enforce report",
		"talon enforce enable",
		"talon enforce disable",
		"`talon enforce`",
		"talon enforce --",
		"--gateway-mode",
		"talon_quickstart_mode",
		"enforcement_mode",
		"shadow_summary",
		"quickstart_shadow_mode",
		"shadow_violations",
		"shadow mode",
		"shadow-mode",
		"mode: shadow",
		"mode: \"shadow\"",
		"mode: passthrough",
		"mode: \"passthrough\"",
		"mode: log_only",
		"mode: \"log_only\"",
		"mode: intercept",
		"mode: \"intercept\"",
		"passthrough mode",
		"log_only mode",
	}

	var violations []string
	for _, root := range scanRoots {
		abs := filepath.Join(repoRoot, root)
		info, err := os.Stat(abs)
		if err != nil {
			continue
		}
		walk := func(path string) {
			if postureAllowlisted(path) || !postureScannableExt(path) {
				return
			}
			violations = append(violations, scanFileForPosture(t, repoRoot, path, patterns, postureFeatureLocalLine)...)
		}
		if info.IsDir() {
			_ = filepath.WalkDir(abs, func(path string, d os.DirEntry, err error) error {
				if err != nil || d.IsDir() {
					return err
				}
				walk(path)
				return nil
			})
		} else {
			walk(abs)
		}
	}

	if len(violations) > 0 {
		shown := len(violations)
		if shown > 60 {
			shown = 60
		}
		t.Errorf("live-posture vocabulary describes the current product in %d user-facing line(s) (#442 guard). Rewrite, or annotate an explicit legacy/migration note with #442:\n%s",
			len(violations), strings.Join(violations[:shown], "\n"))
	}
}

func scanFileForPosture(t *testing.T, repoRoot, path string, patterns []string, featureLocal func(string) bool) []string {
	t.Helper()
	f, err := os.Open(path) // #nosec G304 -- repo-local test walk
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	var out []string
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Text()
		if strings.Contains(line, "#442") {
			continue // explicit migration/legacy note
		}
		lower := strings.ToLower(line)
		if featureLocal(lower) {
			continue
		}
		for _, p := range patterns {
			if strings.Contains(lower, strings.ToLower(p)) {
				rel, _ := filepath.Rel(repoRoot, path)
				out = append(out, rel+":"+itoa(lineNo)+": "+strings.TrimSpace(line))
				break
			}
		}
	}
	return out
}

// postureAllowlisted names the files where removed-posture vocabulary is
// legitimately historical or feature-local.
func postureAllowlisted(path string) bool {
	rel := filepath.ToSlash(path)
	switch {
	case strings.HasSuffix(rel, "CHANGELOG.md"):
		return true // release history is historical by definition
	case strings.Contains(rel, "docs/adr/"), strings.Contains(rel, "docs/contributor/adr/"):
		return true // ADRs are point-in-time records
	case strings.Contains(rel, "docs/assets/"):
		return true // recorded demo casts
	case strings.HasSuffix(rel, "tests/posture_vocabulary_test.go"), strings.HasSuffix(rel, "tests/legacy_nouns_test.go"):
		return true
	case strings.Contains(rel, "examples/auditor-pack/"):
		return true // generated sample export from a historical run; regenerated by `make auditor-pack`
	case strings.HasSuffix(rel, "docs/MEMORY_GOVERNANCE.md"), strings.HasSuffix(rel, "docs/reference/pii-semantic-enrichment.md"), strings.HasSuffix(rel, "docs/PERSONA_GUIDES.md"):
		return true // feature-local memory/enrichment vocabulary (#442 §6 renames later)
	}
	return false
}

// postureFeatureLocalLine matches lines that legitimately say "shadow":
// memory and semantic enrichment evaluation modes, and the attachment
// detector action enum.
func postureFeatureLocalLine(lower string) bool {
	return strings.Contains(lower, "memory") ||
		strings.Contains(lower, "enrichment") ||
		strings.Contains(lower, "action_on_detection") ||
		strings.Contains(lower, "consolidat")
}

func postureScannableExt(path string) bool {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".md", ".yaml", ".yml", ".tmpl", ".sh", ".json", ".rego", ".py", ".ipynb", ".html", ".js":
		return true
	}
	return false
}
