name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: compliance
    attributes:
      label: Compliance requirement (if applicable)
      description: Is this required for GDPR, EU AI Act, NIS2, DORA, etc.?
      placeholder: "GDPR Article X requires..."
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
