package compliance

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var updateGolden = flag.Bool("update-golden", false, "rewrite golden files under testdata/")

// fixedTime keeps golden files deterministic.
var fixedTime = time.Date(2026, 6, 11, 10, 0, 0, 0, time.UTC)

func sampleDocument() Document {
	return Document{
		Title:       "Record of Processing Activities",
		Subtitle:    "Generated by Dativo Talon from signed runtime evidence",
		GeneratedAt: fixedTime,
		Framework:   "gdpr",
		Article:     "Art. 30",
		TenantID:    "acme",
		AgentID:     "support-agent",
		Sections: []DocSection{
			{
				Heading: "1. Controller",
				Body:    "Example GmbH — privacy@example.eu — Examplestr. 1, 10115 Berlin",
			},
			{
				Heading: "2. Recipients of personal data",
				Table: &DocTable{
					Headers: []string{"Recipient", "Kind", "Region", "Records"},
					Rows: [][]string{
						{"openai", "llm_provider", "US", "12"},
						{"mistral-eu", "llm_provider", "EU", "30"},
					},
				},
			},
		},
		Linkage: EvidenceLinkage{
			EvidenceCount:     42,
			From:              "2026-01-01",
			To:                "2026-06-11",
			SampleEvidenceIDs: []string{"req_001", "req_002"},
			VerifyCommand:     "talon audit verify --file evidence.signed.json",
			SignedExportRef:   "evidence.signed.json",
		},
		ClaimNote: ClaimNoteFor("GDPR Art. 30"),
	}
}

func missingSectionDocument() Document {
	doc := sampleDocument()
	doc.Warnings = []string{
		"declaration missing: set compliance.controller.name (talon.config.yaml) — needed for controller identity, GDPR Art. 30(1)(a)",
	}
	doc.Sections[0] = DocSection{
		Heading: "1. Controller",
		Body:    MissingDeclarationText,
		Missing: true,
	}
	return doc
}

func checkGolden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if *updateGolden {
		require.NoError(t, os.MkdirAll("testdata", 0o755))
		require.NoError(t, os.WriteFile(path, got, 0o644))
		return
	}
	want, err := os.ReadFile(path)
	require.NoError(t, err, "golden file %s missing — run: go test ./internal/compliance/ -run TestRenderDocument -update-golden", path)
	assert.Equal(t, string(want), string(got), "output drifted from golden file %s — review and regenerate with -update-golden", path)
}

func TestRenderDocumentJSON_Golden(t *testing.T) {
	out, err := RenderDocumentJSON(sampleDocument())
	require.NoError(t, err)
	checkGolden(t, "document_full.json", out)

	// Output must be valid JSON round-trippable into Document.
	var back Document
	require.NoError(t, json.Unmarshal(out, &back))
	assert.Equal(t, "Record of Processing Activities", back.Title)
	assert.Equal(t, 42, back.Linkage.EvidenceCount)
}

func TestRenderDocumentHTML_Golden(t *testing.T) {
	out, err := RenderDocumentHTML(sampleDocument())
	require.NoError(t, err)
	checkGolden(t, "document_full.html", out)
}

func TestRenderDocumentHTML_MissingSection_Golden(t *testing.T) {
	out, err := RenderDocumentHTML(missingSectionDocument())
	require.NoError(t, err)
	checkGolden(t, "document_missing.html", out)

	html := string(out)
	assert.Contains(t, html, "DECLARATION MISSING", "missing section must be flagged")
	assert.Contains(t, html, "Declarations to complete before auditor handoff")
}

func TestRenderDocumentHTML_EscapesUserInput(t *testing.T) {
	doc := sampleDocument()
	doc.Sections[0].Body = `<script>alert("x")</script>`
	doc.Sections[1].Table.Rows[0][0] = `<img src=x onerror=alert(1)>`

	out, err := RenderDocumentHTML(doc)
	require.NoError(t, err)
	html := string(out)
	assert.NotContains(t, html, "<script>alert", "section body must be escaped")
	assert.NotContains(t, html, "<img src=x", "table cell must be escaped")
	assert.Contains(t, html, "&lt;script&gt;")
}

func TestRenderDocumentHTML_EmptyDocument(t *testing.T) {
	out, err := RenderDocumentHTML(Document{Title: "Empty", GeneratedAt: fixedTime, ClaimNote: ClaimNoteFor("review")})
	require.NoError(t, err)
	assert.Contains(t, string(out), "Empty")
	assert.Contains(t, string(out), "not a completed legal filing")
}

func TestClaimNoteFor(t *testing.T) {
	note := ClaimNoteFor("GDPR Art. 30 and EU AI Act Annex IV")
	assert.True(t, strings.Contains(note, "supporting records"), "must use claims-discipline wording")
	assert.True(t, strings.Contains(note, "not a completed legal filing"), "must disclaim legal effect")
	assert.True(t, strings.Contains(note, "GDPR Art. 30 and EU AI Act Annex IV"))
	assert.False(t, strings.Contains(strings.ToLower(note), "compliant"), "must never claim compliance")
}
